"""Add patient_survey and corporate_survey

Revision ID: 0956d4e3002a
Revises: 74e58a42dacb
Create Date: 2025-07-07 17:50:19.031550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0956d4e3002a'
down_revision: Union[str, None] = '74e58a42dacb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_corporate_codes', sa.Column('patient_survey', sa.JSON(), nullable=False, server_default="{}"))
    op.add_column('appointment_corporate_codes', sa.Column('corporate_survey', sa.JSON(), nullable=False, server_default="{}"))
    op.add_column('patient_appointments', sa.Column('patient_survey', sa.JSON(), nullable=True))
    op.add_column('patient_appointments', sa.Column('corporate_survey', sa.JSON(), nullable=True))
    op.drop_column('patient_appointments', 'survey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_appointments', sa.Column('survey', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('patient_appointments', 'corporate_survey')
    op.drop_column('patient_appointments', 'patient_survey')
    op.drop_column('appointment_corporate_codes', 'corporate_survey')
    op.drop_column('appointment_corporate_codes', 'patient_survey')
    # ### end Alembic commands ###
