"""add_sgimed_invoice_refunds

Revision ID: 201ab68d2bd7
Revises: 5e97c112d05e
Create Date: 2025-06-18 17:16:10.608830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201ab68d2bd7'
down_revision: Union[str, None] = '5e97c112d05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sgimed_invoice_refunds',
    sa.Column('sgimed_invoice_id', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('include_delivery_charges', sa.Boolean(), nullable=False),
    sa.Column('sgimed_invoice_payment_items', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sgimed_invoice_id')
    )
    op.create_index(op.f('ix_sgimed_invoice_refunds_sgimed_invoice_id'), 'sgimed_invoice_refunds', ['sgimed_invoice_id'], unique=False)
    op.add_column('appointment_services', sa.Column('sgimed_inventory_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment_services', 'sgimed_inventory_id')
    op.drop_index(op.f('ix_sgimed_invoice_refunds_sgimed_invoice_id'), table_name='sgimed_invoice_refunds')
    op.drop_table('sgimed_invoice_refunds')
    # ### end Alembic commands ###
