"""add sgimed_patient_given_id field

Revision ID: 32692b5032e9
Revises: f8c802d369a3
Create Date: 2025-07-01 10:01:01.007933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32692b5032e9'
down_revision: Union[str, None] = 'f8c802d369a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_accounts', sa.Column('sgimed_patient_given_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_accounts', 'sgimed_patient_given_id')
    # ### end Alembic commands ###
