"""Add unique constraints to account_id and firebase_uid in patient_firebase_auths

Revision ID: 39a8dd8d0c1e
Revises: 977896e27b33
Create Date: 2025-11-13 11:03:34.507270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a8dd8d0c1e'
down_revision: Union[str, None] = '977896e27b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_patient_firebase_auths_account_id'), 'patient_firebase_auths', ['account_id'], unique=True)
    op.create_index(op.f('ix_patient_firebase_auths_firebase_uid'), 'patient_firebase_auths', ['firebase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_firebase_auths_firebase_uid'), table_name='patient_firebase_auths')
    op.drop_index(op.f('ix_patient_firebase_auths_account_id'), table_name='patient_firebase_auths')
    # ### end Alembic commands ###
