"""Update branch sgimed_branch_id to allow for optional and non unique

Revision ID: 45d64de6594d
Revises: 0956d4e3002a
Create Date: 2025-07-11 14:21:18.879079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d64de6594d'
down_revision: Union[str, None] = '0956d4e3002a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pinnacle_branches', 'sgimed_branch_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_pinnacle_branches_sgimed_branch_id', table_name='pinnacle_branches')
    op.create_index(op.f('ix_pinnacle_branches_sgimed_branch_id'), 'pinnacle_branches', ['sgimed_branch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pinnacle_branches_sgimed_branch_id'), table_name='pinnacle_branches')
    op.create_index('ix_pinnacle_branches_sgimed_branch_id', 'pinnacle_branches', ['sgimed_branch_id'], unique=True)
    op.alter_column('pinnacle_branches', 'sgimed_branch_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
