"""Add sgimed_appointment_type_id to Branch table

Revision ID: 4ba1b28ab0cb
Revises: a1b2c3d4e5f6
Create Date: 2025-11-04 13:19:47.694043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba1b28ab0cb'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pinnacle_branches', sa.Column('sgimed_appointment_type_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pinnacle_branches', 'sgimed_appointment_type_id')
    # ### end Alembic commands ###
