"""Add refund_details to YuuTransactionLog

Revision ID: 60d16c309c1c
Revises: 7d3315861d84
Create Date: 2025-06-25 19:57:28.425190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d16c309c1c'
down_revision: Union[str, None] = '7d3315861d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yuu_transaction_logs', sa.Column('refund_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yuu_transaction_logs', 'refund_details')
    # ### end Alembic commands ###
