"""Add appointment corporate code to support only primary patient

Revision ID: 72aee85898c7
Revises: 8e2d4f98243a
Create Date: 2025-09-23 20:19:27.569311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72aee85898c7'
down_revision: Union[str, None] = '8e2d4f98243a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_corporate_codes', sa.Column('only_primary_user', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment_corporate_codes', 'only_primary_user')
    # ### end Alembic commands ###
