"""add prepayment and display price

Revision ID: 74e58a42dacb
Revises: 32692b5032e9
Create Date: 2025-07-07 13:39:52.380650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e58a42dacb'
down_revision: Union[str, None] = '32692b5032e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_services', sa.Column('prepayment_price', sa.Float(), nullable=False, server_default='0'))
    op.add_column('appointment_services', sa.Column('display_price', sa.Float(), nullable=False, server_default='0'))
    op.create_foreign_key(None, 'appointment_services', 'sgimed_inventory', ['sgimed_inventory_id'], ['id'])
    op.drop_column('appointment_services', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_services', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointment_services', type_='foreignkey')
    op.drop_column('appointment_services', 'display_price')
    op.drop_column('appointment_services', 'prepayment_price')
    # ### end Alembic commands ###
