"""add_delivery_tables

Revision ID: 7d3315861d84
Revises: 201ab68d2bd7
Create Date: 2025-06-18 22:39:26.547307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d3315861d84'
down_revision: Union[str, None] = '201ab68d2bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'RETRY', 'NO_DELIVERY_SERVICE', name='deliverystatus').create(op.get_bind())
    sa.Enum('NORTH', 'SOUTH', 'EAST', 'WEST', 'CENTRAL', 'UNKNOWN', name='deliveryzone').create(op.get_bind())
    op.create_table('teleconsult_delivery_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sector_code', sa.String(), nullable=False),
    sa.Column('zone', postgresql.ENUM('NORTH', 'SOUTH', 'EAST', 'WEST', 'CENTRAL', 'UNKNOWN', name='deliveryzone', create_type=False), nullable=False),
    sa.Column('has_service', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teleconsult_delivery_zones_sector_code'), 'teleconsult_delivery_zones', ['sector_code'], unique=True)
    op.create_table('teleconsult_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teleconsult_id', sa.Uuid(), nullable=False),
    sa.Column('zone', postgresql.ENUM('NORTH', 'SOUTH', 'EAST', 'WEST', 'CENTRAL', 'UNKNOWN', name='deliveryzone', create_type=False), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('postal', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'RETRY', 'NO_DELIVERY_SERVICE', name='deliverystatus', create_type=False), nullable=False),
    sa.Column('dispatch_history', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('is_migrant', sa.Boolean(), nullable=False),
    sa.Column('number_of_packages', sa.Integer(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('delivery_attempt', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('receipt_date', sa.DateTime(), nullable=True),
    sa.Column('is_delivery_note_exists', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('delivery_note_file_path', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('dispatch_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['pinnacle_accounts.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_accounts.id'], ),
    sa.ForeignKeyConstraint(['teleconsult_id'], ['teleconsult_queues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teleconsult_deliveries_dispatch_id'), 'teleconsult_deliveries', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_teleconsult_deliveries_patient_id'), 'teleconsult_deliveries', ['patient_id'], unique=False)
    op.create_index(op.f('ix_teleconsult_deliveries_teleconsult_id'), 'teleconsult_deliveries', ['teleconsult_id'], unique=False)
    op.sync_enum_values(
        enum_schema='public',
        enum_name='role',
        new_values=['SUPERADMIN', 'ADMIN', 'DOCTOR', 'LOGISTIC', 'DISPATCH'],
        affected_columns=[TableReference(table_schema='public', table_name='pinnacle_accounts', column_name='role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='role',
        new_values=['SUPERADMIN', 'ADMIN', 'DOCTOR'],
        affected_columns=[TableReference(table_schema='public', table_name='pinnacle_accounts', column_name='role')],
        enum_values_to_rename=[],
    )
    op.drop_index(op.f('ix_teleconsult_deliveries_teleconsult_id'), table_name='teleconsult_deliveries')
    op.drop_index(op.f('ix_teleconsult_deliveries_patient_id'), table_name='teleconsult_deliveries')
    op.drop_index(op.f('ix_teleconsult_deliveries_dispatch_id'), table_name='teleconsult_deliveries')
    op.drop_table('teleconsult_deliveries')
    op.drop_index(op.f('ix_teleconsult_delivery_zones_sector_code'), table_name='teleconsult_delivery_zones')
    op.drop_table('teleconsult_delivery_zones')
    sa.Enum('NORTH', 'SOUTH', 'EAST', 'WEST', 'CENTRAL', 'UNKNOWN', name='deliveryzone').drop(op.get_bind())
    sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'RETRY', 'NO_DELIVERY_SERVICE', name='deliverystatus').drop(op.get_bind())
    # ### end Alembic commands ###
