"""Add optional title column to Appointments

Revision ID: 8e2d4f98243a
Revises: d3af70adf6bd
Create Date: 2025-09-21 22:25:23.036768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2d4f98243a'
down_revision: Union[str, None] = 'd3af70adf6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_service_groups', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment_service_groups', 'title')
    # ### end Alembic commands ###
