"""Add unsupported_branches to service groups and services

Revision ID: 977896e27b33
Revises: 4ba1b28ab0cb
Create Date: 2025-11-04 15:16:21.951811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '977896e27b33'
down_revision: Union[str, None] = '4ba1b28ab0cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_service_groups', sa.Column('unsupported_branches', sa.ARRAY(sa.String(), dimensions=1), nullable=False, server_default='{}'))
    op.add_column('appointment_services', sa.Column('unsupported_branches', sa.ARRAY(sa.String(), dimensions=1), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment_services', 'unsupported_branches')
    op.drop_column('appointment_service_groups', 'unsupported_branches')
    # ### end Alembic commands ###
