"""Add start_date and end_date to appointment_service_groups

Revision ID: a1b2c3d4e5f6
Revises: 04cff2d54b49
Create Date: 2025-10-14 07:54:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '04cff2d54b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_service_groups', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointment_service_groups', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment_service_groups', 'end_date')
    op.drop_column('appointment_service_groups', 'start_date')
    # ### end Alembic commands ###
