"""Added new appointment cols

Revision ID: d3af70adf6bd
Revises: 45d64de6594d
Create Date: 2025-07-28 11:38:02.966601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3af70adf6bd'
down_revision: Union[str, None] = '45d64de6594d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_service_groups', sa.Column('restricted_memberships', sa.ARRAY(sa.String(), dimensions=1), nullable=False, server_default='{}'))
    op.add_column('patient_appointments', sa.Column('affiliate_code', sa.String(), nullable=True))
    op.add_column('patient_appointments', sa.Column('notifications_sent', sa.ARRAY(sa.String(), dimensions=1), nullable=False, server_default='{}'))
    op.alter_column('patient_appointments', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_appointments', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('patient_appointments', 'notifications_sent')
    op.drop_column('patient_appointments', 'affiliate_code')
    op.drop_column('appointment_service_groups', 'restricted_memberships')
    # ### end Alembic commands ###
