"""add_appointment_category

Revision ID: d44af2046d9c
Revises: be5f87ab3afa
Create Date: 2025-11-25 15:21:44.178663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd44af2046d9c'
down_revision: Union[str, None] = 'be5f87ab3afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('GENERAL', 'SPECIALIST', name='appointmentcategory').create(op.get_bind())
    op.add_column('appointment_corporate_codes', sa.Column('category', postgresql.ENUM('GENERAL', 'SPECIALIST', name='appointmentcategory', create_type=False), nullable=False, server_default='GENERAL'))
    op.add_column('appointment_onsite_branches', sa.Column('category', postgresql.ENUM('GENERAL', 'SPECIALIST', name='appointmentcategory', create_type=False), nullable=False, server_default='GENERAL'))
    op.add_column('appointment_service_groups', sa.Column('category', postgresql.ENUM('GENERAL', 'SPECIALIST', name='appointmentcategory', create_type=False), nullable=False, server_default='GENERAL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment_service_groups', 'category')
    op.drop_column('appointment_onsite_branches', 'category')
    op.drop_column('appointment_corporate_codes', 'category')
    sa.Enum('GENERAL', 'SPECIALIST', name='appointmentcategory').drop(op.get_bind())
    # ### end Alembic commands ###
