"""update_delivery_tables

Revision ID: f8c802d369a3
Revises: 60d16c309c1c
Create Date: 2025-06-30 21:38:14.268275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c802d369a3'
down_revision: Union[str, None] = '60d16c309c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teleconsult_deliveries', 'delivery_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('teleconsult_delivery_zones', sa.Column('is_migrant_area', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teleconsult_delivery_zones', 'is_migrant_area')
    op.alter_column('teleconsult_deliveries', 'delivery_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
