// AUTO-GENERATED - do not hand-edit.
// Every dialCode here exists in the backend PhoneCountryCode enum, so the login endpoint
// can never reject a selection from this list with a 422.
// maxLength is the national part only: E.164 caps a full number at 15 digits including
// the country code, so 14 is the ceiling. Singapore keeps its exact 8-digit format.
// Format rules are enforced by isValidMobileNumber in apis/user.ts - keep them in sync.

export interface Country {
  name: string;
  code: string;
  dialCode: string;
  flag: string;
  maxLength: number;
}

export const COUNTRIES: Country[] = [
  { name: 'Singapore', code: 'SG', dialCode: '+65', flag: '🇸🇬', maxLength: 8 },
  { name: 'Andorra', code: 'AD', dialCode: '+376', flag: '🇦🇩', maxLength: 14 },
  { name: 'Angola', code: 'AO', dialCode: '+244', flag: '🇦🇴', maxLength: 14 },
  { name: 'Anguilla', code: 'AI', dialCode: '+1264', flag: '🇦🇮', maxLength: 14 },
  { name: 'Antarctica', code: 'AQ', dialCode: '+672', flag: '🇦🇶', maxLength: 14 },
  { name: 'Antigua & Barbuda', code: 'AG', dialCode: '+1268', flag: '🇦🇬', maxLength: 14 },
  { name: 'Argentina', code: 'AR', dialCode: '+54', flag: '🇦🇷', maxLength: 14 },
  { name: 'Armenia', code: 'AM', dialCode: '+374', flag: '🇦🇲', maxLength: 14 },
  { name: 'Aruba', code: 'AW', dialCode: '+297', flag: '🇦🇼', maxLength: 14 },
  { name: 'Australia', code: 'AU', dialCode: '+61', flag: '🇦🇺', maxLength: 14 },
  { name: 'Austria', code: 'AT', dialCode: '+43', flag: '🇦🇹', maxLength: 14 },
  { name: 'Azerbaijan', code: 'AZ', dialCode: '+994', flag: '🇦🇿', maxLength: 14 },
  { name: 'Bahamas', code: 'BS', dialCode: '+1242', flag: '🇧🇸', maxLength: 14 },
  { name: 'Bahrain', code: 'BH', dialCode: '+973', flag: '🇧🇭', maxLength: 14 },
  { name: 'Bangladesh', code: 'BD', dialCode: '+880', flag: '🇧🇩', maxLength: 14 },
  { name: 'Barbados', code: 'BB', dialCode: '+1246', flag: '🇧🇧', maxLength: 14 },
  { name: 'Belarus', code: 'BY', dialCode: '+375', flag: '🇧🇾', maxLength: 14 },
  { name: 'Belgium', code: 'BE', dialCode: '+32', flag: '🇧🇪', maxLength: 14 },
  { name: 'Belize', code: 'BZ', dialCode: '+501', flag: '🇧🇿', maxLength: 14 },
  { name: 'Benin', code: 'BJ', dialCode: '+229', flag: '🇧🇯', maxLength: 14 },
  { name: 'Bermuda', code: 'BM', dialCode: '+1441', flag: '🇧🇲', maxLength: 14 },
  { name: 'Bhutan', code: 'BT', dialCode: '+975', flag: '🇧🇹', maxLength: 14 },
  { name: 'Bolivia', code: 'BO', dialCode: '+591', flag: '🇧🇴', maxLength: 14 },
  { name: 'Bosnia & Herzegovina', code: 'BA', dialCode: '+387', flag: '🇧🇦', maxLength: 14 },
  { name: 'Botswana', code: 'BW', dialCode: '+267', flag: '🇧🇼', maxLength: 14 },
  { name: 'Brazil', code: 'BR', dialCode: '+55', flag: '🇧🇷', maxLength: 14 },
  { name: 'Brunei', code: 'BN', dialCode: '+673', flag: '🇧🇳', maxLength: 14 },
  { name: 'Bulgaria', code: 'BG', dialCode: '+359', flag: '🇧🇬', maxLength: 14 },
  { name: 'Burkina Faso', code: 'BF', dialCode: '+226', flag: '🇧🇫', maxLength: 14 },
  { name: 'Burundi', code: 'BI', dialCode: '+257', flag: '🇧🇮', maxLength: 14 },
  { name: 'Cabo Verde', code: 'CV', dialCode: '+238', flag: '🇨🇻', maxLength: 14 },
  { name: 'Cambodia', code: 'KH', dialCode: '+855', flag: '🇰🇭', maxLength: 14 },
  { name: 'Cameroon', code: 'CM', dialCode: '+237', flag: '🇨🇲', maxLength: 14 },
  { name: 'Canada / United States', code: 'US', dialCode: '+1', flag: '🇺🇸', maxLength: 14 },
  { name: 'Cayman Islands', code: 'KY', dialCode: '+1345', flag: '🇰🇾', maxLength: 14 },
  { name: 'Central African Republic', code: 'CF', dialCode: '+236', flag: '🇨🇫', maxLength: 14 },
  { name: 'Chile', code: 'CL', dialCode: '+56', flag: '🇨🇱', maxLength: 14 },
  { name: 'China', code: 'CN', dialCode: '+86', flag: '🇨🇳', maxLength: 14 },
  { name: 'Colombia', code: 'CO', dialCode: '+57', flag: '🇨🇴', maxLength: 14 },
  { name: 'Comoros', code: 'KM', dialCode: '+269', flag: '🇰🇲', maxLength: 14 },
  { name: 'Congo - Brazzaville', code: 'CG', dialCode: '+242', flag: '🇨🇬', maxLength: 14 },
  { name: 'Cook Islands', code: 'CK', dialCode: '+682', flag: '🇨🇰', maxLength: 14 },
  { name: 'Costa Rica', code: 'CR', dialCode: '+506', flag: '🇨🇷', maxLength: 14 },
  { name: 'Croatia', code: 'HR', dialCode: '+385', flag: '🇭🇷', maxLength: 14 },
  { name: 'Cuba', code: 'CU', dialCode: '+53', flag: '🇨🇺', maxLength: 14 },
  { name: 'Cyprus', code: 'CY', dialCode: '+357', flag: '🇨🇾', maxLength: 14 },
  { name: 'Denmark', code: 'DK', dialCode: '+45', flag: '🇩🇰', maxLength: 14 },
  { name: 'Djibouti', code: 'DJ', dialCode: '+253', flag: '🇩🇯', maxLength: 14 },
  { name: 'Ecuador', code: 'EC', dialCode: '+593', flag: '🇪🇨', maxLength: 14 },
  { name: 'Egypt', code: 'EG', dialCode: '+20', flag: '🇪🇬', maxLength: 14 },
  { name: 'El Salvador', code: 'SV', dialCode: '+503', flag: '🇸🇻', maxLength: 14 },
  { name: 'Equatorial Guinea', code: 'GQ', dialCode: '+240', flag: '🇬🇶', maxLength: 14 },
  { name: 'Eritrea', code: 'ER', dialCode: '+291', flag: '🇪🇷', maxLength: 14 },
  { name: 'Estonia', code: 'EE', dialCode: '+372', flag: '🇪🇪', maxLength: 14 },
  { name: 'Eswatini', code: 'SZ', dialCode: '+268', flag: '🇸🇿', maxLength: 14 },
  { name: 'Ethiopia', code: 'ET', dialCode: '+251', flag: '🇪🇹', maxLength: 14 },
  { name: 'Falkland Islands', code: 'FK', dialCode: '+500', flag: '🇫🇰', maxLength: 14 },
  { name: 'Faroe Islands', code: 'FO', dialCode: '+298', flag: '🇫🇴', maxLength: 14 },
  { name: 'Fiji', code: 'FJ', dialCode: '+679', flag: '🇫🇯', maxLength: 14 },
  { name: 'Finland', code: 'FI', dialCode: '+358', flag: '🇫🇮', maxLength: 14 },
  { name: 'France', code: 'FR', dialCode: '+33', flag: '🇫🇷', maxLength: 14 },
  { name: 'French Guiana', code: 'GF', dialCode: '+594', flag: '🇬🇫', maxLength: 14 },
  { name: 'French Polynesia', code: 'PF', dialCode: '+689', flag: '🇵🇫', maxLength: 14 },
  { name: 'Gabon', code: 'GA', dialCode: '+241', flag: '🇬🇦', maxLength: 14 },
  { name: 'Gambia', code: 'GM', dialCode: '+220', flag: '🇬🇲', maxLength: 14 },
  { name: 'Germany', code: 'DE', dialCode: '+49', flag: '🇩🇪', maxLength: 14 },
  { name: 'Ghana', code: 'GH', dialCode: '+233', flag: '🇬🇭', maxLength: 14 },
  { name: 'Gibraltar', code: 'GI', dialCode: '+350', flag: '🇬🇮', maxLength: 14 },
  { name: 'Greece', code: 'GR', dialCode: '+30', flag: '🇬🇷', maxLength: 14 },
  { name: 'Greenland', code: 'GL', dialCode: '+299', flag: '🇬🇱', maxLength: 14 },
  { name: 'Grenada', code: 'GD', dialCode: '+1473', flag: '🇬🇩', maxLength: 14 },
  { name: 'Guadeloupe', code: 'GP', dialCode: '+590', flag: '🇬🇵', maxLength: 14 },
  { name: 'Guatemala', code: 'GT', dialCode: '+502', flag: '🇬🇹', maxLength: 14 },
  { name: 'Guinea', code: 'GN', dialCode: '+224', flag: '🇬🇳', maxLength: 14 },
  { name: 'Guinea-Bissau', code: 'GW', dialCode: '+245', flag: '🇬🇼', maxLength: 14 },
  { name: 'Guyana', code: 'GY', dialCode: '+592', flag: '🇬🇾', maxLength: 14 },
  { name: 'Haiti', code: 'HT', dialCode: '+509', flag: '🇭🇹', maxLength: 14 },
  { name: 'Honduras', code: 'HN', dialCode: '+504', flag: '🇭🇳', maxLength: 14 },
  { name: 'Hong Kong SAR China', code: 'HK', dialCode: '+852', flag: '🇭🇰', maxLength: 14 },
  { name: 'Hungary', code: 'HU', dialCode: '+36', flag: '🇭🇺', maxLength: 14 },
  { name: 'Iceland', code: 'IS', dialCode: '+354', flag: '🇮🇸', maxLength: 14 },
  { name: 'India', code: 'IN', dialCode: '+91', flag: '🇮🇳', maxLength: 14 },
  { name: 'Indonesia', code: 'ID', dialCode: '+62', flag: '🇮🇩', maxLength: 14 },
  { name: 'Iran', code: 'IR', dialCode: '+98', flag: '🇮🇷', maxLength: 14 },
  { name: 'Iraq', code: 'IQ', dialCode: '+964', flag: '🇮🇶', maxLength: 14 },
  { name: 'Ireland', code: 'IE', dialCode: '+353', flag: '🇮🇪', maxLength: 14 },
  { name: 'Israel', code: 'IL', dialCode: '+972', flag: '🇮🇱', maxLength: 14 },
  { name: 'Italy', code: 'IT', dialCode: '+39', flag: '🇮🇹', maxLength: 14 },
  { name: 'Japan', code: 'JP', dialCode: '+81', flag: '🇯🇵', maxLength: 14 },
  { name: 'Jordan', code: 'JO', dialCode: '+962', flag: '🇯🇴', maxLength: 14 },
  { name: 'Kazakhstan', code: 'KZ', dialCode: '+7', flag: '🇰🇿', maxLength: 14 },
  { name: 'Kenya', code: 'KE', dialCode: '+254', flag: '🇰🇪', maxLength: 14 },
  { name: 'Kiribati', code: 'KI', dialCode: '+686', flag: '🇰🇮', maxLength: 14 },
  { name: 'Kuwait', code: 'KW', dialCode: '+965', flag: '🇰🇼', maxLength: 14 },
  { name: 'Kyrgyzstan', code: 'KG', dialCode: '+996', flag: '🇰🇬', maxLength: 14 },
  { name: 'Laos', code: 'LA', dialCode: '+856', flag: '🇱🇦', maxLength: 14 },
  { name: 'Latvia', code: 'LV', dialCode: '+371', flag: '🇱🇻', maxLength: 14 },
  { name: 'Lebanon', code: 'LB', dialCode: '+961', flag: '🇱🇧', maxLength: 14 },
  { name: 'Lesotho', code: 'LS', dialCode: '+266', flag: '🇱🇸', maxLength: 14 },
  { name: 'Liberia', code: 'LR', dialCode: '+231', flag: '🇱🇷', maxLength: 14 },
  { name: 'Libya', code: 'LY', dialCode: '+218', flag: '🇱🇾', maxLength: 14 },
  { name: 'Lithuania', code: 'LT', dialCode: '+370', flag: '🇱🇹', maxLength: 14 },
  { name: 'Luxembourg', code: 'LU', dialCode: '+352', flag: '🇱🇺', maxLength: 14 },
  { name: 'Macao SAR China', code: 'MO', dialCode: '+853', flag: '🇲🇴', maxLength: 14 },
  { name: 'Madagascar', code: 'MG', dialCode: '+261', flag: '🇲🇬', maxLength: 14 },
  { name: 'Malawi', code: 'MW', dialCode: '+265', flag: '🇲🇼', maxLength: 14 },
  { name: 'Malaysia', code: 'MY', dialCode: '+60', flag: '🇲🇾', maxLength: 14 },
  { name: 'Maldives', code: 'MV', dialCode: '+960', flag: '🇲🇻', maxLength: 14 },
  { name: 'Mali', code: 'ML', dialCode: '+223', flag: '🇲🇱', maxLength: 14 },
  { name: 'Malta', code: 'MT', dialCode: '+356', flag: '🇲🇹', maxLength: 14 },
  { name: 'Marshall Islands', code: 'MH', dialCode: '+692', flag: '🇲🇭', maxLength: 14 },
  { name: 'Martinique', code: 'MQ', dialCode: '+596', flag: '🇲🇶', maxLength: 14 },
  { name: 'Mauritania', code: 'MR', dialCode: '+222', flag: '🇲🇷', maxLength: 14 },
  { name: 'Mauritius', code: 'MU', dialCode: '+230', flag: '🇲🇺', maxLength: 14 },
  { name: 'Mayotte', code: 'YT', dialCode: '+262', flag: '🇾🇹', maxLength: 14 },
  { name: 'Mexico', code: 'MX', dialCode: '+52', flag: '🇲🇽', maxLength: 14 },
  { name: 'Micronesia', code: 'FM', dialCode: '+691', flag: '🇫🇲', maxLength: 14 },
  { name: 'Moldova', code: 'MD', dialCode: '+373', flag: '🇲🇩', maxLength: 14 },
  { name: 'Monaco', code: 'MC', dialCode: '+377', flag: '🇲🇨', maxLength: 14 },
  { name: 'Mongolia', code: 'MN', dialCode: '+976', flag: '🇲🇳', maxLength: 14 },
  { name: 'Morocco', code: 'MA', dialCode: '+212', flag: '🇲🇦', maxLength: 14 },
  { name: 'Mozambique', code: 'MZ', dialCode: '+258', flag: '🇲🇿', maxLength: 14 },
  { name: 'Myanmar (Burma)', code: 'MM', dialCode: '+95', flag: '🇲🇲', maxLength: 14 },
  { name: 'Namibia', code: 'NA', dialCode: '+264', flag: '🇳🇦', maxLength: 14 },
  { name: 'Nauru', code: 'NR', dialCode: '+674', flag: '🇳🇷', maxLength: 14 },
  { name: 'Nepal', code: 'NP', dialCode: '+977', flag: '🇳🇵', maxLength: 14 },
  { name: 'Netherlands', code: 'NL', dialCode: '+31', flag: '🇳🇱', maxLength: 14 },
  { name: 'New Caledonia', code: 'NC', dialCode: '+687', flag: '🇳🇨', maxLength: 14 },
  { name: 'New Zealand', code: 'NZ', dialCode: '+64', flag: '🇳🇿', maxLength: 14 },
  { name: 'Nicaragua', code: 'NI', dialCode: '+505', flag: '🇳🇮', maxLength: 14 },
  { name: 'Niger', code: 'NE', dialCode: '+227', flag: '🇳🇪', maxLength: 14 },
  { name: 'Nigeria', code: 'NG', dialCode: '+234', flag: '🇳🇬', maxLength: 14 },
  { name: 'Niue', code: 'NU', dialCode: '+683', flag: '🇳🇺', maxLength: 14 },
  { name: 'North Korea', code: 'KP', dialCode: '+850', flag: '🇰🇵', maxLength: 14 },
  { name: 'Norway', code: 'NO', dialCode: '+47', flag: '🇳🇴', maxLength: 14 },
  { name: 'Oman', code: 'OM', dialCode: '+968', flag: '🇴🇲', maxLength: 14 },
  { name: 'Palau', code: 'PW', dialCode: '+680', flag: '🇵🇼', maxLength: 14 },
  { name: 'Panama', code: 'PA', dialCode: '+507', flag: '🇵🇦', maxLength: 14 },
  { name: 'Papua New Guinea', code: 'PG', dialCode: '+675', flag: '🇵🇬', maxLength: 14 },
  { name: 'Paraguay', code: 'PY', dialCode: '+595', flag: '🇵🇾', maxLength: 14 },
  { name: 'Peru', code: 'PE', dialCode: '+51', flag: '🇵🇪', maxLength: 14 },
  { name: 'Philippines', code: 'PH', dialCode: '+63', flag: '🇵🇭', maxLength: 14 },
  { name: 'Poland', code: 'PL', dialCode: '+48', flag: '🇵🇱', maxLength: 14 },
  { name: 'Portugal', code: 'PT', dialCode: '+351', flag: '🇵🇹', maxLength: 14 },
  { name: 'Qatar', code: 'QA', dialCode: '+974', flag: '🇶🇦', maxLength: 14 },
  { name: 'Romania', code: 'RO', dialCode: '+40', flag: '🇷🇴', maxLength: 14 },
  { name: 'Rwanda', code: 'RW', dialCode: '+250', flag: '🇷🇼', maxLength: 14 },
  { name: 'Saint Helena', code: 'SH', dialCode: '+290', flag: '🇸🇭', maxLength: 14 },
  { name: 'San Marino', code: 'SM', dialCode: '+378', flag: '🇸🇲', maxLength: 14 },
  { name: 'Sao Tome & Principe', code: 'ST', dialCode: '+239', flag: '🇸🇹', maxLength: 14 },
  { name: 'Saudi Arabia', code: 'SA', dialCode: '+966', flag: '🇸🇦', maxLength: 14 },
  { name: 'Senegal', code: 'SN', dialCode: '+221', flag: '🇸🇳', maxLength: 14 },
  { name: 'Serbia', code: 'RS', dialCode: '+381', flag: '🇷🇸', maxLength: 14 },
  { name: 'Seychelles', code: 'SC', dialCode: '+248', flag: '🇸🇨', maxLength: 14 },
  { name: 'Sierra Leone', code: 'SL', dialCode: '+232', flag: '🇸🇱', maxLength: 14 },
  { name: 'Slovakia', code: 'SK', dialCode: '+421', flag: '🇸🇰', maxLength: 14 },
  { name: 'Slovenia', code: 'SI', dialCode: '+386', flag: '🇸🇮', maxLength: 14 },
  { name: 'Solomon Islands', code: 'SB', dialCode: '+677', flag: '🇸🇧', maxLength: 14 },
  { name: 'Somalia', code: 'SO', dialCode: '+252', flag: '🇸🇴', maxLength: 14 },
  { name: 'South Africa', code: 'ZA', dialCode: '+27', flag: '🇿🇦', maxLength: 14 },
  { name: 'South Korea', code: 'KR', dialCode: '+82', flag: '🇰🇷', maxLength: 14 },
  { name: 'Spain', code: 'ES', dialCode: '+34', flag: '🇪🇸', maxLength: 14 },
  { name: 'Sri Lanka', code: 'LK', dialCode: '+94', flag: '🇱🇰', maxLength: 14 },
  { name: 'Sudan', code: 'SD', dialCode: '+249', flag: '🇸🇩', maxLength: 14 },
  { name: 'Suriname', code: 'SR', dialCode: '+597', flag: '🇸🇷', maxLength: 14 },
  { name: 'Sweden', code: 'SE', dialCode: '+46', flag: '🇸🇪', maxLength: 14 },
  { name: 'Switzerland', code: 'CH', dialCode: '+41', flag: '🇨🇭', maxLength: 14 },
  { name: 'Syria', code: 'SY', dialCode: '+963', flag: '🇸🇾', maxLength: 14 },
  { name: 'Taiwan', code: 'TW', dialCode: '+886', flag: '🇹🇼', maxLength: 14 },
  { name: 'Thailand', code: 'TH', dialCode: '+66', flag: '🇹🇭', maxLength: 14 },
  { name: 'Timor-Leste', code: 'TL', dialCode: '+670', flag: '🇹🇱', maxLength: 14 },
  { name: 'Togo', code: 'TG', dialCode: '+228', flag: '🇹🇬', maxLength: 14 },
  { name: 'Tonga', code: 'TO', dialCode: '+676', flag: '🇹🇴', maxLength: 14 },
  { name: 'Tunisia', code: 'TN', dialCode: '+216', flag: '🇹🇳', maxLength: 14 },
  { name: 'Turkey', code: 'TR', dialCode: '+90', flag: '🇹🇷', maxLength: 14 },
  { name: 'Turkmenistan', code: 'TM', dialCode: '+993', flag: '🇹🇲', maxLength: 14 },
  { name: 'Tuvalu', code: 'TV', dialCode: '+688', flag: '🇹🇻', maxLength: 14 },
  { name: 'Uganda', code: 'UG', dialCode: '+256', flag: '🇺🇬', maxLength: 14 },
  { name: 'Ukraine', code: 'UA', dialCode: '+380', flag: '🇺🇦', maxLength: 14 },
  { name: 'United Arab Emirates', code: 'AE', dialCode: '+971', flag: '🇦🇪', maxLength: 14 },
  { name: 'United Kingdom', code: 'GB', dialCode: '+44', flag: '🇬🇧', maxLength: 14 },
  { name: 'Uruguay', code: 'UY', dialCode: '+598', flag: '🇺🇾', maxLength: 14 },
  { name: 'Vanuatu', code: 'VU', dialCode: '+678', flag: '🇻🇺', maxLength: 14 },
  { name: 'Vatican City', code: 'VA', dialCode: '+379', flag: '🇻🇦', maxLength: 14 },
  { name: 'Venezuela', code: 'VE', dialCode: '+58', flag: '🇻🇪', maxLength: 14 },
  { name: 'Vietnam', code: 'VN', dialCode: '+84', flag: '🇻🇳', maxLength: 14 },
  { name: 'Wallis & Futuna', code: 'WF', dialCode: '+681', flag: '🇼🇫', maxLength: 14 },
];
